<a href="https://colab.research.google.com/github/Phunbie/assignments/blob/main/Session__1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

Question 2

In [3]:
pd.__version__

'1.1.5'

Question 1

In [4]:
np.__version__

'1.19.5'

In [8]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'

In [9]:
df = pd.read_csv(url)

In [10]:
df.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

Question 3

In [11]:
df['MSRP'].mean()

40594.737032063116

Question 4

In [12]:
df[df.Year>= 2015].isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

Question 5

In [17]:
mean_hp_before = df['Engine HP'].mean()
mean_hp_before

249.38607007176023

In [16]:
hp_after = df['Engine HP'].fillna(mean_hp_before)
hp_after.isna().sum()

0

In [18]:
mean_hp_after = hp_after.mean()
mean_hp_after

249.38607007176

In [19]:
print(round(mean_hp_before))

249


In [20]:
print(round(mean_hp_after))

249


Question 6

In [25]:
X = np.array(df[["Engine HP", "Engine Cylinders", "highway MPG"]][df.Make == "Rolls-Royce"].drop_duplicates())
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [38]:
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [43]:
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [44]:
XTXInv = np.linalg.inv(XTX)
XTXInv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [45]:
XTXInv.sum()

0.032212320677486125

Questions 7

In [34]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [49]:
w =(XTXInv.dot(X.T)) * y
w


array([[  -4.86592076,    3.70158161,   -0.44514862,    1.72227877,
          -1.39491731,   -1.98126399,    3.46328627],
       [-190.20088338,  102.98797193,  -75.41225048,    5.90042376,
         229.97158839,   -5.18427392,  -37.03645368],
       [ 251.64624904, -152.77517227,   65.62358801,  -39.58285347,
         -97.39786221,   62.38667397,  -58.24683429]])